# fly.toml app configuration file generated for phoenix-ash-chat on 2023-07-04T14:13:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phoenix-ash-chat"
primary_region = "den"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "phoenix-ash-chat.fly.dev"
  PHX_SERVER = true
  PORT = "8080"
  APPSIGNAL_OTP_APP="ash_chat"
  APPSIGNAL_APP_NAME="ash_chat"
  APPSIGNAL_APP_ENV="prod"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
