defmodule App.Repo.Migrations.AddPhotoToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :photo_url, :text
    end
  end

  def down do
    alter table(:users) do
      remove :photo_url
    end
  end
end
