defmodule App.Repo.Migrations.AddLastReadTimeToMember do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel_member) do
      add :last_read_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:channel_member) do
      remove :last_read_at
    end
  end
end
