defmodule App.Repo.Migrations.AddEditedToMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:message) do
      add :edited, :boolean, default: false
    end
  end

  def down do
    alter table(:message) do
      remove :edited
    end
  end
end
