defmodule App.Repo.Migrations.AddMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:message, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :text, :text, null: false

      add :channel_id,
          references(:channel,
            column: :id,
            name: "message_channel_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sender_id,
          references(:users,
            column: :id,
            name: "message_sender_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:message, "message_channel_id_fkey")

    drop constraint(:message, "message_sender_id_fkey")

    drop table(:message)
  end
end
