defmodule App.Repo.Migrations.AddChannelMembers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:channel_member, primary_key: false) do
      add :channel_id,
          references(:channel,
            column: :id,
            name: "channel_member_channel_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "channel_member_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:channel_member, "channel_member_channel_id_fkey")

    drop constraint(:channel_member, "channel_member_user_id_fkey")

    drop table(:channel_member)
  end
end
