defmodule App.Repo.Migrations.AddPrivateToChannel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channel) do
      add :private, :boolean, default: false
    end
  end

  def down do
    alter table(:channel) do
      remove :private
    end
  end
end
